version: '3.8'

services:
  db:
    restart: unless-stopped
    image: postgres
    volumes:
      - tri-postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: triathlon-api

  redis:
    image: redis:latest
    network_mode: service:db
    volumes:
      - tri-redis-data:/data

volumes:
  tri-postgres-data:
  tri-redis-data:
